### ISSUE TITLE
Extra version's substring in filename

### ISSUE THREAD

**Issue by doctornkz** [crazy-max/ghaction-xgo#247]
#### Steps to reproduce this issue

1. Create action with configuration
```
      - name: Generate build files
        uses: crazy-max/ghaction-xgo@v2
        with:
          xgo_version: latest
          go_version: 1.18
          dest: build
          pkg: "cmd/encarno"
          prefix: ${{ github.event.repository.name }}
          targets: linux/amd64, linux/arm64, darwin/amd64, darwin/arm64, windows/amd64
          v: true
          x: false
          race: false
          ldflags: -s -w
          buildmode: default
          buildvcs: false
          tags: ""
      - name: Checking artifacts
        run: ls -la build
      - name: Release artifacts
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: > 
            build/${{ github.event.repository.name }}-darwin-10.16-amd64,
            build/${{ github.event.repository.name }}-darwin-10.16-arm64,
            build/${{ github.event.repository.name }}-linux-amd64,
            build/${{ github.event.repository.name }}-linux-arm64,
            build/${{ github.event.repository.name }}-windows-4.0-amd64.exe
          allowUpdates: 'true'
          token: ${{ secrets.GITHUB_TOKEN }}
```
2. Run action 
3. Check the output directory

#### Expected behavior
We should see templated filename as
`project_name-platform-architecture[.ext]`

```
%NAME%-darwin-amd64
%NAME%-darwin-arm64
%NAME%-linux-amd64
%NAME%-linux-arm64
%NAME%-windows-amd64.exe
```
#### Actual behaviour

We have filename as 
`project_name-platform-[???]-architecture[.ext]`

```
%NAME%-darwin-10.16-amd64
%NAME%-darwin-10.16-arm64
%NAME%-linux-amd64
%NAME%-linux-arm64
%NAME%-windows-4.0-amd64.exe
```

It can break links in documentation or in Dockerfile. Is it possible to switch them off?

### Configuration

* Repository URL (public): https://github.com/doctornkz/encarno
* Build URL (if public): https://github.com/doctornkz/encarno/runs/6860470823?check_suite_focus=true

```yml
# workflow name
name: Generate release-artifacts

# on events
on:
  push:
    tags: 
        - "*.*"

# workflow tasks
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.0.2
      - name: Generate build files
        uses: crazy-max/ghaction-xgo@v2
        with:
          xgo_version: latest
          go_version: 1.18
          dest: build
          pkg: "cmd/encarno"
          prefix: ${{ github.event.repository.name }}
          targets: linux/amd64, linux/arm64, darwin/amd64, darwin/arm64, windows/amd64
          v: true
          x: false
          race: false
          ldflags: -s -w
          buildmode: default
          buildvcs: ""
          tags: ""
      - name: Checking artifacts
        run: ls -la build
      - name: Release artifacts
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: > 
            build/${{ github.event.repository.name }}-darwin-10.16-amd64,
            build/${{ github.event.repository.name }}-darwin-10.16-arm64,
            build/${{ github.event.repository.name }}-linux-amd64,
            build/${{ github.event.repository.name }}-linux-arm64,
            build/${{ github.event.repository.name }}-windows-4.0-amd64.exe
          allowUpdates: 'true'
          token: ${{ secrets.GITHUB_TOKEN }}
```
