### ISSUE TITLE
Error: Unexpected HTTP response: 404, miss linux_x86_64 release in 0.26.0

### ISSUE THREAD

**Issue by moonD4rk** [crazy-max/ghaction-xgo#269]
It seems that this error has occurred before https://github.com/crazy-max/ghaction-xgo/issues/259 and was fixed in this PR https://github.com/crazy-max/ghaction-xgo/pull/258, but in version 0.26.0, the binary file for `linux_x86_64` was forgotten to be released.

GitHub actions error info
```
Run crazy-max/ghaction-xgo@v1
  with:
    xgo_version: latest
    dest: build
    prefix: hack-browser-data
    pkg: cmd/hack-browser-data
    targets: windows/amd64,windows/386,linux/386,linux/amd64,linux/arm,linux/arm64,darwin/amd64
    v: true
    x: false
    race: false
    ldflags: -s -w
    buildmode: default
    docker-repo: ghcr.io/crazy-max/xgo
Download and install xgo
  Downloading https://github.com/crazy-max/xgo/releases/download/v0.26.0/xgo_0.26.0_linux_x86_64.tar.gz
  Error: Unexpected HTTP response: 404
```

My action file
```yaml
name: Release
on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v1

      - name: Use Golang
        uses: actions/setup-go@v1
        with:
          go-version: "1.20"

      - name: Build with xgo
        uses: crazy-max/ghaction-xgo@v1
        with:
          xgo_version: latest
          go_version: ${{ matrix.go_version }}
          dest: build
          prefix: hack-browser-data
          pkg: cmd/hack-browser-data
          targets: windows/amd64,windows/386,linux/386,linux/amd64,linux/arm,linux/arm64,darwin/amd64
          # targets: windows/amd64,windows/386,darwin/amd64,linux/arm
          v: true
          x: false
          race: false
          ldflags: -s -w
          buildmode: default 
...
```

**Comment by crazy-max** [comment]
Looks good on ci: https://github.com/crazy-max/ghaction-xgo/actions/runs/4391747486/jobs/7691095244#step:3:16

Can you remove `xgo_version: latest` and let me know if it works?

**Comment by moonD4rk** [comment]
After remove `xgo_version: latest ` 

``` yaml
name: Release
on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v1

      - name: Use Golang
        uses: actions/setup-go@v1
        with:
          go-version: "1.20"

      - name: Build with xgo
        uses: crazy-max/ghaction-xgo@v1
        with:
          go_version: ${{ matrix.go_version }}
          dest: build
          prefix: hack-browser-data
          pkg: cmd/hack-browser-data
          targets: windows/amd64,windows/386,linux/386,linux/amd64,linux/arm,linux/arm64,darwin/amd64
          # targets: windows/amd64,windows/386,darwin/amd64,linux/arm
          v: true
          x: false
          race: false
          ldflags: -s -w
          buildmode: default 

```
And the [log](https://github.com/uinfziuna8n/HackBrowserData/actions/runs/4392654018/jobs/7692555697) is same 

```
Run crazy-max/ghaction-xgo@v1
  with:
    dest: build
    prefix: hack-browser-data
    pkg: cmd/hack-browser-data
    targets: windows/amd64,windows/386,linux/386,linux/amd64,linux/arm,linux/arm64,darwin/amd64
    v: true
    x: false
    race: false
    ldflags: -s -w
    buildmode: default
    xgo_version: latest
    docker-repo: ghcr.io/crazy-max/xgo
  env:
    GOROOT: /opt/hostedtoolcache/go/1.20.2/x64
Download and install xgo
  Downloading https://github.com/crazy-max/xgo/releases/download/v0.26.0/xgo_0.26.0_linux_x86_64.tar.gz
  Error: Unexpected HTTP response: 404

```


It seems that there is no release related to linux_x86_64 under tag [v0.26.0](https://github.com/crazy-max/xgo/releases/tag/v0.26.0), while there is one for linux_x86_64 under tag [v0.23.0](https://github.com/crazy-max/xgo/releases/tag/v0.23.0).
