### ISSUE TITLE
go_version is misread

### ISSUE THREAD

**Issue by deitch** [crazy-max/ghaction-xgo#311]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/ghaction-xgo/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Passing `go_version: 1.20` is treated as `1.2`, which causes it to fail to download the container image.

### Expected behaviour

It should treat go 1.20 as 1.20 and not 1.2

### Actual behaviour

It thinks 1.20 is 1.2 and then fails to download the image

### Steps to reproduce

Use the above config and watch it fail.

### Repository URL

https://github.com/databacker/mysql-backup

### Workflow run URL

https://github.com/databacker/mysql-backup/actions/runs/7485946836/job/20375327323

### YAML workflow

```yaml
- name: Build with xgo
        uses: crazy-max/ghaction-xgo@v3
        with:
          xgo_version: latest
          go_version: 1.20
          dest: dist
          targets: windows/386,windows/amd64,windows/arm64,linux/386,linux/amd64,linux/arm64,darwin/amd64,darwin/arm64
          v: true
          x: true
          ldflags: -s -w
```

### Workflow logs

Run crazy-max/ghaction-xgo@v3
  with:
    xgo_version: latest
    go_version: 1.2       <==== THIS BECAME 1.2 🤷‍♂️ 
    dest: dist
    targets: windows/386,windows/amd64,windows/arm64,linux/386,linux/amd64,linux/arm64,darwin/amd64,darwin/arm64
    v: true
    x: true
    ldflags: -s -w
    race: false
    buildmode: default
    trimpath: false
...
INFO: Checking for required docker image ghcr.io/crazy-max/xgo:1.2... 
not found!
INFO: Pulling ghcr.io/crazy-max/xgo:1.2 from docker registry...
Error response from daemon: manifest unknown
ERROR: Failed to pull docker image from the registry: exit status 1.
